# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'animation_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_animation_widget(object):
    def setupUi(self, animation_widget):
        animation_widget.setObjectName("animation_widget")
        animation_widget.resize(836, 417)
        self.verticalLayout = QtWidgets.QVBoxLayout(animation_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.canvas_widget = CanvasWidget(animation_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas_widget.sizePolicy().hasHeightForWidth())
        self.canvas_widget.setSizePolicy(sizePolicy)
        self.canvas_widget.setObjectName("canvas_widget")
        self.verticalLayout.addWidget(self.canvas_widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_pushButton = QtWidgets.QPushButton(animation_widget)
        self.start_pushButton.setObjectName("start_pushButton")
        self.horizontalLayout.addWidget(self.start_pushButton)
        self.stop_pushButton = QtWidgets.QPushButton(animation_widget)
        self.stop_pushButton.setObjectName("stop_pushButton")
        self.horizontalLayout.addWidget(self.stop_pushButton)
        self.reset_pushButton = QtWidgets.QPushButton(animation_widget)
        self.reset_pushButton.setObjectName("reset_pushButton")
        self.horizontalLayout.addWidget(self.reset_pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.option_pushButton = QtWidgets.QPushButton(animation_widget)
        self.option_pushButton.setObjectName("option_pushButton")
        self.horizontalLayout.addWidget(self.option_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(animation_widget)
        QtCore.QMetaObject.connectSlotsByName(animation_widget)

    def retranslateUi(self, animation_widget):
        _translate = QtCore.QCoreApplication.translate
        animation_widget.setWindowTitle(_translate("animation_widget", "Form"))
        self.start_pushButton.setText(_translate("animation_widget", "Start"))
        self.stop_pushButton.setText(_translate("animation_widget", "Stop"))
        self.reset_pushButton.setText(_translate("animation_widget", "Reset"))
        self.option_pushButton.setText(_translate("animation_widget", "Optionen"))
from canvas import CanvasWidget
